# Generated by Django 3.2 on 2021-12-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_competitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Not More Than 50 Characters', max_length=50)),
                ('picture', models.FileField(upload_to='uploads/')),
                ('contestant_code', models.CharField(help_text='must be unique, Characters less than 10', max_length=10, unique=True)),
                ('short_bio', models.CharField(help_text='not more than 200 characters', max_length=200)),
                ('number_of_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(help_text='Not more than 150 characters', max_length=150)),
                ('picture', models.FileField(upload_to='uploads/')),
                ('price_per_vote', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
